services:

  # envoy, configured as with envoy.yaml to use extprocs
  envoy:
    image: envoyproxy/envoy:${ENVOY_VERSION:-v1.29-latest}
    ports:
      - "8080:8000"
      - "9901:9901"
    volumes:
      - ./internal/integration/testdata/envoy.yaml:/etc/envoy/envoy.yaml
      - ./tmp:/tmp/blah:rw

  # upstream "echo" server
  upstream:
    hostname: upstream
    image: echo-server:${IMAGE_TAG:-compose}
    build:
      context: _mocks/echo
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    environment:
      - LOG_LEVEL=info

  # extprocs
#  multiplex:
#    image: envoy-extproc-sdk-go-examples:${IMAGE_TAG:-compose}
#    command:
#      - multiplex
  noop:
    image: envoy-extproc-sdk-go-examples:${IMAGE_TAG:-compose}
    command:
      - ALL
#      - '-network'
#      - unix
#      - '-address'
#      - /tmp/blah/blah.sock
    volumes:
      - ./tmp:/tmp/blah:rw
    environment:
      - LOG_LEVEL=info

#  trivial:
#    image: envoy-extproc-sdk-go-examples:${IMAGE_TAG:-compose}
#    command:
#      - trivial
#  timer:
#    image: envoy-extproc-sdk-go-examples:${IMAGE_TAG:-compose}
#    command:
#      - timer
#  data:
#    image: envoy-extproc-sdk-go-examples:${IMAGE_TAG:-compose}
#    command:
#      - data
#  digest:
#    image: envoy-extproc-sdk-go-examples:${IMAGE_TAG:-compose}
#    command:
#      - digest
#  dedup:
#    image: envoy-extproc-sdk-go-examples:${IMAGE_TAG:-compose}
#    command:
#      - dedup
#  masker:
#    image: envoy-extproc-sdk-go-examples:${IMAGE_TAG:-compose}
#    command:
#      - masker
#  echo:
#    image: envoy-extproc-sdk-go-examples:${IMAGE_TAG:-compose}
#    command:
#      - echo
#  wasm:
#    image: envoy-extproc-sdk-go-examples:${IMAGE_TAG:-compose}
#    command:
#      - wasm
