services:

  # envoy, configured as with envoy.yaml to use extprocs
  envoy:
    image: envoyproxy/envoy:${ENVOY_VERSION:-v1.29-latest}
    ports:
      - "8080:8000"
      - "9901:9901"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml

  # extprocs
  multiplex:
    image: envoy-extproc-sdk-go-examples:${IMAGE_TAG:-compose}
    command:
      - multiplex
